[[section-introduction-and-goals]]
== Introducción y Objetivos

[role="arc42help"]
****
El objetivo de este proyecto es la creación de un chat descentralizado, es decir, una aplicacion o programa mediante el cual dos o mas usuarios se comuniquen entre si de forma tal que la informacion transcurrida entre ellos no sea almacenada ni circule por ningun servidor externo, evitando asi, la perdidia de la confidencialidad de los datos y permitiendo conversaciones realmente privadas a diferencia de otros softwares.

Para conseguir esta descentralizacion usaremos el framework SOLID, cada uno de los usuarios deberá poseer un POD de SOLID y una de ellos correrá el Server Solid
****

=== Requisitos

[role="arc42help"]
****
La aplicación contendrá una vista principal de los usuarios con los que la persona "protagonista" podrá comunicarse. Tras seleccionar uno de ellos, será capaz de poder enviar mensajes y recibirlos. En un principio implementaremos solo los mensajes, mas adelante nos gustaria dar la posibilidad de transmision de imagenes o incluso videos.


****

=== Quality Goals

[role="arc42help"]
****

Con este proyecto aspiramos a conseguir una comunicacion privada y de punto a punto real entre los usuarios, evitando así filtraciones de información o problemas de seguridad. Nuestros objetivos ordenados por orden de prioridad serían:

-Conversaciones textuales fluidas entre dos usuarios.
-Enviar o recibir archivos de tipo audiovisual.
-Permitir la opcion de conversaciones grupales de mas de 2 usuarios.
-Interfaz cuidada y accesible.
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
|===
|Role/Name|Contact|Expectations
| _<Clientes>_ | _<Los usuarios de "a pié" de la aplicación>_ | _<Poder comunicarse con contactos deseados>_
| _<Profesores>_ | _<Profesores de la asignatura>_ | _<Aplicación de chat descentralizada y accesible usando SOLID>_
| _<SOLID Staffs'>_ | _<Desarrolladores y componentes de SOLID>_ | _<Aplicacion usable, accesible y comercial que use SOLID de manera correcta>_
|===
****

[options="header",cols="1,2,2"]
