[[section-introduction-and-goals]]

== Introduction and goals

****
The main goal of this project is to create a decentralized chat, better said, an application or program through two or more people can communicate in a way that all the information does not pass through any external server, avoiding lose confidenciality of the data, allowing real private conversations, not like other softwares.

We are going to use SOLID framework to get that decentralization. Every user must have a SOLID POD to login and use our application
****

=== Requirements

****

The application will have a "home" with a list of the users who the "protagonist" could communicate. After selecting one of them, he will be able to send and receive messages. First we are going to implement just sending messages, then, we would like to add the posibility of pictures transmission, or even video recordings.

****

=== Quality goals

****

With this project we must seek to get a real private peer to peer communication between users, avoiding information leaks or security probles. Our Quality scenarios are: 
****
[options="header",cols="1,2,3"]
|===
| *AQ* | *Scenario* | *Priority*
| Functional suitability | The application must correctly meet the minimum requirements for a conversation to take place between two users| High, high
| Usability | The application must be easy to understand and use to satisfy the user| High, medium
| Efficiency | The sending of messages must be correctly reaching the receiver in reasonable times | High, medium
| Testability | The application must pass unit tests and integration tests correctly | High, medium
| Maintainability | 
Ensuring continuous improvement against errors, unexpected component failures and new requirements | Medium, high
| Securability | Require each user to identify themselves in order to use the application and allow them to control who has access to their data | Medium, medium
| Scalability | Although the number of users increases, the application will continue to operate with the same efficiency| Medium, medium
|===
****

****

=== Stakeholders

****
The users whom the aplication is directed are exposed just below. All the users must be capable of login the application and communicate
|===
|Rol|Contact|Expectations
| _Client_ | _Regular users of the application_ | _Communicate with another contact_
| _Teachers_ | _Teachers of the subject_ | _Decentralized and accesible application using SOLID_
| _SOLID STAFF'S_ | _SOLID Developers and employees | _Usable, accesible and "comercial" aplication with a correct use of SOLID_
|===
[options="header",cols="1,2,2"]
****

[[section-introduction-and-goals]]

