[[section-introduction-and-goals]]

== Introduction and goals

****
The main goal of this project is to create a decentralized chat, better said, an application or program through two or more people can communicate in a way that all the information does not pass through any external server, avoiding lose confidentiality of the data, allowing real private conversations, not like other software.

We are going to use SOLID framework to get that decentralization. Every user must have a SOLID POD to log in and use our application
****

=== Requirements

****

The application will have a "home" with a list of the users who the "protagonist" could communicate. After selecting one of them, he will be able to send and receive messages. First, we are going to implement just sending messages, then, we would like to add the possibility of pictures transmission, or even video recordings.

****

=== Quality goals

****

With this project we must seek to get a real private peer to peer communication between users, avoiding information leaks or security problems. Our most important quality scenarios are:
****

. Functional suitability -> The application must correctly meet the minimum requirements for a conversation to take place between two users. At the first place we want a basic text conversation
. Usability -> The application must be easy to use. All users must be able to use the application, even users with little knowledge.
. Efficiency -> The time between sending and receiving messages must be reasonable.
. Testability -> The application must pass our unit test without any problem.

****

****

=== Stakeholders

****
The users whom the application is directed are exposed just below. All the users must be capable of log in the application and communicate
|===
|Rol|Contact|Expectations
| _Client_ | _Regular users of the application_ | _Communicate with another contact_
| _Teachers_ | _Teachers of the subject_ | _Decentralized and accesible application using SOLID_
| _SOLID STAFF'S_ | _SOLID Developers and employees_ | _Usable, accesible and "comercial" aplication with a correct use of https://solid.inrupt.com/[SOLID]_
|===
[options="header",cols="1,2,2"]
****

[[section-introduction-and-goals]]

