[[section-design-decisions]]
== Design Decisions

== Architecture
Peer-to-Peer (P2P). This architecture is used in a Solid application

=== Language
Among the following three languages:

* Java
* C#
* AngujarJS (JavaScript)

We have decided that the best language is JavaScript since the other two languages (Java and C #) do not have direct support of Solid and it would be us who would have to implement a controller that communicates with SOLID. However, the disadvantage of JavaScript is that we need a level that no member of the team currently has. Despite this, among all we have seen that the best option is to use JavaScript.

=== Database
For the moment we will not use any database because we do not see it necessary. As the project progresses, if we see that the project requires a database, we will use a relational database such as MySQL, as we have used them in other subjects and we already have some experience with them.

== Decisiones de Diseño

== Arquitectura
Red entre pares (P2P). Esta arquitectura es usada en una aplicación de Solid.

=== Lenguaje
Entre los siguientes tres lenguajes:

* Java
* C#
* AngujarJS (JavaScript)

Hemos decidido que el mejor lenguaje es JavaScript ya que los otros dos lenguajes(Java y C#) no tienen soporte directo de Solid y seríamos nosotros los que tendríamos que implementar un controlador que comunique con SOLID. Sin embargo, la desventaja de JavaScript es que necesitamos un nivel que de momento ningún miembro del equipo tiene. A pesar de esto, entre todos hemos visto que la mejor opción es utilizar JavaScript.

=== Base de Datos
De momento no vamos a utilizar ninguna base de datos ya que no lo vemos necesario. A medida que avance el proyecto, si vemos que el proyecto requiere de una base de datos, usaríamos una base de datos relacional como por ejemplo MySQL, ya que las hemos utilizado en otras asignaturas y ya tenemos cierta experiencia con ellas.
