= Reunion 1 (Meeting 1)

=Español (Spanish):

==Objetivos

Decidir lenguaje en el que implementar la aplicación ademas de el tipo de base de
datos que vamos a utilizar y intentar comenzar con la organización del trabajo.

== Asistentes

- Alba Serena Suárez
- David Rico Díaz
- Yago García Rodríguez

== Base de datos

Por el momento preferimos no definir el tipo de base de datos a usar debido
a que se decide comenzar con el proyecto, entender el funcionamiento de SOLID
y como acomplarlo al codigo. Mas adelante cuando necesitemos una Base de datos
y comentemos dudas con el profesor comenzaremos con la creacion de la base.
Lo que si hemos decidido es que será un modelo de Base de Datos relacional,
como por ejemplo MySQL.


== Lenguaje

Partimos de la propuesta de los sifuientes lenguajes:
-Java
-C#
-AngularJS (JavaScript)

Finalmente descartamos Java y C# por no tener un soporte directo de SOLID y
tener que implementar nosotros de forma adicional un controlador que comunique
con SOLID. Debido a esto nos vemos obligados a utilizar Angular JavaScript a pesar de
ser usuarios muy "noveles" en este lenguaje y a cambio seamos mucho mas experimentados
en los anteriormente nombrados.

== Organización del trabajo

Comenzamos con la organizacion del trabajo por el principio, es decir, la documentacion
inicial. Decidimos dividirlo en varios puntos y intentamos repartirlos de forma
equitativa. En total la documentacion esta dividida en 12 puntos, de los cuales
nos repartimos el 1, 2, 4 , 9, 10 y 11. Los puntos restantes creemos que todavia no
tenemos el conocimiento necesario por lo cual los dejaremos para mas adelante.

La descripción de los puntos es la siguiente:

1- Introducción y Objetivos (Introduction and Goals)
2- Restricciones del proyecto (Constraints)
4- Estrategia de solucionar reestricciones (Solution Strategy)
9- Decisiones de la arquitectura de la aplicación (Architectural Decisions)
10- Requisitos de calidad. (Quality requirements)
11- Riesgos (Risk and technical debt).

Como somos 4 componentes en el grupo lo dividiremos de la siguiente manera:

-Persona 1: Punto 1
-Persona 2: Punto 10
-Persona 3: Punto 11 y 9
-Persona 4: Punto 2 y 4.

Trás un sorteo los resultados son los siguientes:
-David: Persona 4.
-Alba: Persona 3.
-Yago: Persona 1.
-Mar: Persona 2.

=English (Inglés):

==Goals
Decide what programming language should we use to implement the main application
, the type of DataBase we are going to use and how organize the job between
us.

==Participants

-Alba Serena Suárez
-David Rico Díaz
-Yago García Rodríguez

==Database

We prefer to not define the structure of the DataBase we are going to use. We
think that is better to learn about SOLID and how to connect it with our code.
When we need a database we are going to use a relacional one, like MySQL

==Language

After a short Brain storm we consider this languages:
-Java
-C#
-Angular JS (JavaScript)

We decide to use AngularJS even though we don't have experience on it. We are more
used to program in Java and C#. All the examples and introduction codes are in this Languages
and SOLID has direct support to them.

==Work Organization

Firt of all we have to do all the documentation or at least a first version of it.
We can divide it in a few separated points and then distribute them between us.
All the documentation is divided in 12 points of which we distribute 1, 2, 4, 9,
10 and 11 the rest we leave it for later because we don't have the knowledge to do them.

We are 4 components so we are going to divide it this way:

-Person 1: Point 1
-Person 2: Point 10
-Person 3: Points 11 y 9
-Person 4: Points 2 y 4.

After a raffle the final results are:
-David: Person 4.
-Alba: Person 3.
-Yago: Person 1.
-Mar: Person 2.
