[[section-solution-strategy]]

== Solution Strategy


****

Because of our little experience on the Software Architecture World some or this early decisions may change in the future
if better technologies are discovered.

* Technology decisions:

The language selected to create de application is going to be JavaScript. It was selected because it's good integration with SOLID.
The use of SOLID will make a decentralized chat using PODS so we assume no database will be needed. In case it's finally needed 
we would use a SQL database because of our knowelge about this database type.

The grafic interface will be done using html and css, this and angular will make our app run both in Desktop computers and smartphones.

* Decisions about the top-level decomposition of the system:

Because of the angular framework it will be easier to implement a MVC(Model View Controller) to have a better organization o the code 

* Decisions on how to achieve key quality goals:

* Organizational decisions:

The decisions about organization will be agile, we will have meetings every week were we will distribute the tasks.

****

