[[section-technical-risks]]
== Risks and Technical Debts

List of identified technical risks or technical debts, ordered by priority

* *Inexperience with the technology that we must use:* One of the requirements is using the SOLID platform in our application. Being a new technology, we have to learn.
* *Loss of time to specialize in a programming language:* We have decided to use a language (JavaScript) of which we have a slight notion. This can delay us when carrying out the project. However, if we had chosen another language we would have to learn how to adapt that language to the SOLID platform. Therefore, comparing the advantages and disadvantages of each one, we decided that it was best to use the language previously mentioned.
* *Loss of team members:* This could harm us in the future since we are 4 in the team and could cause us to delay with deliveries.
* *Little applications on which to base ourselves:* Being a practically new technology, there are hardly any projects that we can use as an example.

To minimize each of the risks we decided that it was best to learn about SOLID and Javascript with a small application by following the steps that appear on this page: https://solid.inrupt.com/docs/writing-solid-apps-with-angular so that when faced with the application, the problems are not so big and we already have part of the work done. We also commit ourselves to help each other so that deliveries are on time.
